# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  $vmname: 'windows-2019'

pool:
  vmImage: '$vmname'

steps:
- task: AzurePowerShell@5
  displayName: run powershell script to get vnet details
  inputs:
    azureSubscription: 'aks_powershell_connection'
    ScriptType: 'FilePath'
    ScriptPath: '$(Build.SourcesDirectory)/vnet.ps1'
    ScriptArguments: '-$rsg aks -$vnet aks_vnet'
    azurePowerShellVersion: LatestVersion
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CopyFiles@2
  displayName: copy output file to stagging directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'powershell-output'
    publishLocation: 'Container'